site_name: Genies Avatar SDK
nav: 
  - Overview: 
    # - index.md
    - overview.md
    # - Getting started: gettingstarted.md
  - Avatar API:
    - api_overview.md
  # - API:
  #   - Authentication: authentication.md
  #   - Managed Anonymous Users: managed_users.md
  #   - Avatar API: assetsapi.md
  #   - Renderer API: renderer.md
  - Avatar Creator SDK:
    - creator_overview.md
  # - Avatar Creator:
  #   - creator_overview.md
  #   - avatar_creator.md
  # # - User management: usermanagement.md
  # # - Avatar: avatarapi.md
  # # - Composer: composer.md
  # - Android: android.md
  # - iOS: ios.md
  - Roadmap: roadmap.md
  - Support: support.md

  # - About: about.md
theme: 
  name: material
  favicon: img/favicon.ico
  features:
    - toc.integrate
    - navigation.expand
    - navigation.tabs
    # - navigation.sections
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: "#"
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list